<?php
$env_items = array();
$dirfile_items = array(
		array('type' => 'dir', 'path' => 'system/cache'),
		array('type' => 'dir', 'path' => 'system/cache/shopwt'),
		array('type' => 'dir', 'path' => 'system/cache/rec_position'),
		array('type' => 'dir', 'path' => 'system/config'),
		array('type' => 'dir', 'path' => 'system/log'),
		array('type' => 'dir', 'path' => 'system/session'),
		array('type' => 'dir', 'path' => 'system/static/phpqrcode/temp'),
		array('type' => 'dir', 'path' => 'system/upfiles'),
		array('type' => 'dir', 'path' => 'system/upfiles/shop/activity'),
		array('type' => 'dir', 'path' => 'system/upfiles/shop/shopwt'),
		array('type' => 'dir', 'path' => 'system/upfiles/shop/article'),
		array('type' => 'dir', 'path' => 'system/upfiles/shop/avatar'),
		array('type' => 'dir', 'path' => 'system/upfiles/shop/brand'),
		array('type' => 'dir', 'path' => 'system/upfiles/shop/common'),
		array('type' => 'dir', 'path' => 'system/upfiles/shop/complain'),
		array('type' => 'dir', 'path' => 'system/upfiles/shop/editor'),
		array('type' => 'dir', 'path' => 'system/upfiles/shop/goods_class'),
		array('type' => 'dir', 'path' => 'system/upfiles/shop/robbuy'),
		array('type' => 'dir', 'path' => 'system/upfiles/shop/inform'),
		array('type' => 'dir', 'path' => 'system/upfiles/shop/login'),
		array('type' => 'dir', 'path' => 'system/upfiles/shop/member'),
		array('type' => 'dir', 'path' => 'system/upfiles/shop/membertag'),
		array('type' => 'dir', 'path' => 'system/upfiles/shop/pointprod'),
		array('type' => 'dir', 'path' => 'system/upfiles/shop/rec_position'),
		array('type' => 'dir', 'path' => 'system/upfiles/shop/refund'),
		array('type' => 'dir', 'path' => 'system/upfiles/shop/store'),
		array('type' => 'dir', 'path' => 'system/upfiles/shop/voucher'),
		array('type' => 'dir', 'path' => 'system/upfiles/shop/watermark'),
		array('type' => 'dir', 'path' => 'system/upfiles/bbs'),
		array('type' => 'dir', 'path' => 'system/upfiles/news'),
		array('type' => 'dir', 'path' => 'system/upfiles/what'),
		array('type' => 'dir', 'path' => 'system/upfiles/since'),
		array('type' => 'dir', 'path' => 'system/upfiles/store'),
		array('type' => 'dir', 'path' => 'system/upfiles/mobile'),
		array('type' => 'dir', 'path' => 'system/upfiles/mobile/mowt'),
		array('type' => 'dir', 'path' => 'system/upfiles/mobile/category'),
		array('type' => 'dir', 'path' => 'system/upfiles/mobile/home'),
		array('type' => 'dir', 'path' => 'system/upfiles/mobile/special'),
		array('type' => 'dir', 'path' => 'system/upfiles/wt/avatar'),
		array('type' => 'dir', 'path' => 'system/backup'),
		array('type' => 'dir', 'path' => 'install'),
);

$func_items = array(
		array('name' => 'mysqli_connect'),
		array('name' => 'fsockopen'),
		array('name' => 'gethostbyname'),
		array('name' => 'file_get_contents'),
		array('name' => 'mb_convert_encoding'),
		array('name' => 'json_encode'),
		array('name' => 'curl_init'),
);